export const produtos = [
  {
    id: 1,
    tipo: 'Smartphone',
    marca: 'Samsung',
    modelo: 'S10 Plus, 128GB, 8GB RAM',
    descricao:
      'Smartphone Samsung Galaxy S10 Plus com 128GB de armazenamento interno e 8GB RAM',
    cor: 'Azul',
    condicao: 'Usado e recondicionado',
    foto: 'https://m.media-amazon.com/images/I/41+hk6RUpPL._AC_.jpg',
    preco: 1650.0,
    garantia: '3 meses',
  },
  {
    id: 2,
    tipo: 'Fone de ouvido',
    marca: 'HyperX',
    modelo: 'Cloud Earbuds',
    descricao: 'Fone de ouvido intra-auricular gamer, HyperX Cloud Earbuds',
    cor: 'Vermelho',
    condicao: 'Novo',
    foto: 'https://cf.shopee.com.br/file/4ea39ed339f88589e14d86a083ecf781',
    preco: 249.9,
    garantia: '3 meses',
  },
  {
    id: 3,
    tipo: 'Tripé',
    marca: 'VX Case',
    modelo: '',
    descricao: 'Tripé profissional para smartphones e câmeras',
    cor: 'Preto',
    condicao: 'Novo',
    foto: 'https://vxcase.vteximg.com.br/arquivos/ids/267748-1000-1000/acessorios-vxcase-21020.png',
    preco: 159.99,
    garantia: '3 meses',
  },
];
