export const produtos = [
  {
    id: 1,
    tipo: 'Smartphone',
    marca: 'Samsung',
    modelo: 'S10 Plus',
    descricao: '128GB, 8GB RAM',
    cor: 'Azul',
    condicao: 'Usado e recondicionado',
    foto: 'https://m.media-amazon.com/images/I/41+hk6RUpPL._AC_.jpg',
    preco: 'R$1.650',
  },
  {
    id: 2,
    tipo: 'Fone de ouvido',
    marca: 'HyperX',
    modelo: 'Cloud Earbuds',
    descricao: 'Intra-Auricular Gamer',
    cor: 'Vermelho',
    condicao: 'Novo',
    foto: 'https://cf.shopee.com.br/file/4ea39ed339f88589e14d86a083ecf781',
    preco: 'R$249,90',
  },
  {
    id: 3,
    tipo: 'Tripé',
    marca: 'VX Case',
    modelo: '',
    descricao: 'Tripé profissional para smartphones e câmera',
    cor: 'Preto',
    condicao: 'Novo',
    foto: 'https://vxcase.vteximg.com.br/arquivos/ids/267748-1000-1000/acessorios-vxcase-21020.png',
    preco: 'R$159,99',
  },
];
